import { Schema } from "effect"

/**
 * Branded identifiers. Ids are opaque strings generated by the IdGenerator port;
 * the brand prevents mixing a FeedId with an EntryId at compile time.
 */
export const FeedId = Schema.String.pipe(Schema.brand("FeedId"))
export type FeedId = typeof FeedId.Type

export const EntryId = Schema.String.pipe(Schema.brand("EntryId"))
export type EntryId = typeof EntryId.Type

export const CategoryId = Schema.String.pipe(Schema.brand("CategoryId"))
export type CategoryId = typeof CategoryId.Type

/** Epoch milliseconds. */
export const Timestamp = Schema.Number
export type Timestamp = typeof Timestamp.Type
